#Even Fibonacci numbers
#Problem 2
#Each new term in the Fibonacci sequence is generated by 
#adding the previous two terms. By starting with 1 and 2, 
#the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence 
#whose values do not exceed four million, find the sum 
#of the even-valued terms.

#Script finds correct answer (4613732) in 0.1s.

def sumOfEvenFibonacciNumbersUnderN(n)

  return 0 if n <= 2 
 
  fibonacci = [0,1]
  total = 0

  until fibonacci.last >= n
  	fibonacci << fibonacci.last + fibonacci[-2]
  	total += fibonacci[-1] if fibonacci[-1].even? 
  end

  total 

end

p sumOfEvenFibonacciNumbersUnderN(4000000)
