=begin
	
Pentagon numbers
Problem 44
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. 
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, 
for which their sum and difference are pentagonal and D = |Pk − Pj| 
is minimised; what is the value of D? 
	
=end

#Because I did not know when the first such pairing would occur, I tried
#the following code with 1..2000, but there were no pairs.  The 
#pair occurred between the 2000th and 3000th pentagonal number.  
#It stands to reason the first instance would have the smallest difference,
#which happened to be correct.

#My code finds the answer -- 5482660 -- in 4.3 seconds.

def checkPentagonals

#We use sets to speed the lookup process.

require 'set'

solution = []

#First create an array of the first 3000 pent numbers.

pentagonals = (1..3000).map { |n| n*(3*n-1)/2}.to_set

#This line forms a new array with all combinations of 2 
#pentagonals, and selects only those that have a pentagonal
#difference and sum.

pentagonals = pentagonals.to_a.combination(2).select { |a,b| pentagonals.include?(a+b) && pentagonals.include?((a-b).abs)}

#Finally, this line outputs the difference between the two pentagonals
#found that satisfy the condition.

puts (pentagonals[0][0] - pentagonals[0][1]).abs

end

checkPentagonals